/**
 * SUBLINX — Dados de seed de eventos de fallback (São Paulo / SP).
 *
 * Módulo de dados puro: contém apenas o array de eventos e o helper
 * de datas. A lógica de fallback (filterPublicEvents / withFallback)
 * vive em eventFallback.js, que importa este módulo.
 *
 * Todos os eventos utilizam venues reais de São Paulo, fotografias reais
 * (Unsplash) e links de compra em plataformas oficiais de ingressos.
 */

const DAY = 24 * 60 * 60 * 1000;
function daysFromNow(days, hour = 22) {
  const d = new Date(Date.now() + days * DAY);
  d.setHours(hour, 0, 0, 0);
  return d.toISOString();
}

export const RAW_FALLBACK_EVENTS = [
  {
    id: 'fb-event-001',
    title: 'Techno Night no Audio Club',
    subtitle: 'Lineup internacional de techno',
    genre: 'techno',
    type: 'club',
    category: 'musica',
    location: {
      lat: -23.5270, lng: -46.6690,
      address: 'Av. Francisco Matarazzo, 694 — Barra Funda',
      venue_name: 'Audio Club',
      city: 'São Paulo', state: 'SP', country: 'BR',
    },
    date: daysFromNow(7, 23),
    duration_hours: 8,
    organizer_id: 'fb-organizer-01',
    organizer: 'Audio Club',
    source: 'sublinx_partner',
    trust_level: 'partner',
    is_published: true,
    is_expired: false,
    is_secret: false,
    price: 90, currency: 'BRL',
    image_url: 'https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=800',
    short_description: 'Noite de techno com lineup internacional no Audio Club, um dos principais templos da música eletrônica de São Paulo.',
    current_attendees: 450,
    ticket_status: 'available',
    has_ticketing: true,
    purchase_url: 'https://www.sympla.com.br',
  },
  {
    id: 'fb-event-002',
    title: 'D-Edge — House Session',
    subtitle: 'House e deep house no D-Edge',
    genre: 'house',
    type: 'club',
    category: 'musica',
    location: {
      lat: -23.5945, lng: -46.6835,
      address: 'Av. Antônio Joaquim de Moura Andrade, 1211 — Vila Olímpia',
      venue_name: 'D-Edge',
      city: 'São Paulo', state: 'SP', country: 'BR',
    },
    date: daysFromNow(14, 23),
    duration_hours: 9,
    organizer_id: 'fb-organizer-02',
    organizer: 'D-Edge',
    source: 'sublinx_partner',
    trust_level: 'partner',
    is_published: true,
    is_expired: false,
    is_secret: false,
    price: 120, currency: 'BRL',
    image_url: 'https://images.unsplash.com/photo-1571266028243-d220c6a9f1d4?w=800',
    short_description: 'House e deep house no D-Edge, eleito diversas vezes um dos melhores clubs do mundo.',
    current_attendees: 380,
    ticket_status: 'available',
    has_ticketing: true,
    purchase_url: 'https://shotgun.live',
  },
  {
    id: 'fb-event-003',
    title: 'Cine Joia — Minimal Session',
    subtitle: 'Minimal e techno underground',
    genre: 'minimal',
    type: 'club',
    category: 'musica',
    location: {
      lat: -23.5495, lng: -46.6360,
      address: 'Praça Carlos Gomes, 130 — Sé',
      venue_name: 'Cine Joia',
      city: 'São Paulo', state: 'SP', country: 'BR',
    },
    date: daysFromNow(10, 23),
    duration_hours: 7,
    organizer_id: 'fb-organizer-03',
    organizer: 'Cine Joia',
    source: 'sublinx_partner',
    trust_level: 'verified',
    is_published: true,
    is_expired: false,
    is_secret: false,
    price: 80, currency: 'BRL',
    image_url: 'https://images.unsplash.com/photo-1516280440614-37939bbacd81?w=800',
    short_description: 'Minimal techno no histórico Cine Joia, no coração do centro de São Paulo.',
    current_attendees: 320,
    ticket_status: 'available',
    has_ticketing: true,
    purchase_url: 'https://www.ingresse.com',
  },
  {
    id: 'fb-event-004',
    title: 'Festival no Vale do Anhangabaú',
    subtitle: 'Festival de música eletrônica ao ar livre',
    genre: 'drum_bass',
    type: 'festival',
    category: 'festival',
    location: {
      lat: -23.5430, lng: -46.6380,
      address: 'Vale do Anhangabaú — Centro',
      venue_name: 'Vale do Anhangabaú',
      city: 'São Paulo', state: 'SP', country: 'BR',
    },
    date: daysFromNow(21, 18),
    duration_hours: 10,
    organizer_id: 'fb-organizer-04',
    organizer: 'São Paulo Fest',
    source: 'sublinx_partner',
    trust_level: 'verified',
    is_published: true,
    is_expired: false,
    is_secret: false,
    price: 150, currency: 'BRL',
    image_url: 'https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=800',
    short_description: 'Festival de drum & bass e bass music ao ar livre no Vale do Anhangabaú.',
    current_attendees: 2800,
    ticket_status: 'available',
    has_ticketing: true,
    purchase_url: 'https://www.eventbrite.com.br',
  },
  {
    id: 'fb-event-005',
    title: 'Komplexo Tempo — Trance Night',
    subtitle: 'Psytrance e trance progressivo',
    genre: 'trance',
    type: 'club',
    category: 'musica',
    location: {
      lat: -23.5560, lng: -46.6550,
      address: 'Rua Augusta, 967 — Consolação',
      venue_name: 'Komplexo Tempo',
      city: 'São Paulo', state: 'SP', country: 'BR',
    },
    date: daysFromNow(5, 23),
    duration_hours: 8,
    organizer_id: 'fb-organizer-05',
    organizer: 'Komplexo Tempo',
    source: 'sublinx_partner',
    trust_level: 'partner',
    is_published: true,
    is_expired: false,
    is_secret: false,
    price: 100, currency: 'BRL',
    image_url: 'https://images.unsplash.com/photo-1506157786151-b8491531f063?w=800',
    short_description: 'Psytrance e trance progressivo na Rua Augusta, no Komplexo Tempo.',
    current_attendees: 520,
    ticket_status: 'available',
    has_ticketing: true,
    purchase_url: 'https://www.ticket360.com.br',
  },
  {
    id: 'fb-event-006',
    title: 'Villa Country — Reggae Night',
    subtitle: 'Reggae roots e dub',
    genre: 'reggae',
    type: 'club',
    category: 'musica',
    location: {
      lat: -23.5230, lng: -46.7010,
      address: 'Rua Cardeal Arcoverde, 3000 — Pinheiros',
      venue_name: 'Villa Country',
      city: 'São Paulo', state: 'SP', country: 'BR',
    },
    date: daysFromNow(12, 21),
    duration_hours: 6,
    organizer_id: 'fb-organizer-06',
    organizer: 'Villa Country',
    source: 'sublinx_partner',
    trust_level: 'partner',
    is_published: true,
    is_expired: false,
    is_secret: false,
    price: 70, currency: 'BRL',
    image_url: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=800',
    short_description: 'Noite de reggae roots e dub no tradicional Villa Country em Pinheiros.',
    current_attendees: 290,
    ticket_status: 'available',
    has_ticketing: true,
    purchase_url: 'https://www.sympla.com.br',
  },
  {
    id: 'fb-event-007',
    title: 'Laroc Club — Funk & Hip Hop',
    subtitle: 'Funk, trap e hip hop',
    genre: 'funk',
    type: 'club',
    category: 'festa',
    location: {
      lat: -23.6240, lng: -46.7000,
      address: 'Rua Tucanos, 260 — Chácara Santo Antônio',
      venue_name: 'Laroc Club',
      city: 'São Paulo', state: 'SP', country: 'BR',
    },
    date: daysFromNow(18, 23),
    duration_hours: 7,
    organizer_id: 'fb-organizer-07',
    organizer: 'Laroc Club',
    source: 'sublinx_partner',
    trust_level: 'verified',
    is_published: true,
    is_expired: false,
    is_secret: false,
    price: 110, currency: 'BRL',
    image_url: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800',
    short_description: 'Funk, trap e hip hop com os melhores DJs nacionais no Laroc Club.',
    current_attendees: 610,
    ticket_status: 'available',
    has_ticketing: true,
    purchase_url: 'https://shotgun.live',
  },
  {
    id: 'fb-event-008',
    title: 'Parque Ibirapuera — Acid Open Air',
    subtitle: 'Acid house e experimental',
    genre: 'acid',
    type: 'festival',
    category: 'musica',
    location: {
      lat: -23.5870, lng: -46.6570,
      address: 'Av. Pedro Álvares Cabral — Vila Mariana',
      venue_name: 'Parque Ibirapuera',
      city: 'São Paulo', state: 'SP', country: 'BR',
    },
    date: daysFromNow(28, 16),
    duration_hours: 8,
    organizer_id: 'fb-organizer-08',
    organizer: 'Ibirapuera Open Air',
    source: 'sublinx_partner',
    trust_level: 'partner',
    is_published: true,
    is_expired: false,
    is_secret: false,
    price: 85, currency: 'BRL',
    image_url: 'https://images.unsplash.com/photo-1485579149621-3123dd979885?w=800',
    short_description: 'Acid house e experimental ao ar livre no Parque Ibirapuera.',
    current_attendees: 950,
    ticket_status: 'available',
    has_ticketing: true,
    purchase_url: 'https://www.ingresse.com',
  },
  {
    id: 'fb-event-009',
    title: 'Cariocó Club — Sertanejo Night',
    subtitle: 'Sertanejo universitário ao vivo',
    genre: 'funk',
    type: 'club',
    category: 'festa',
    location: {
      lat: -23.4980, lng: -46.6780,
      address: 'Av. Ministro Petrônio Portela, 1001 — Freguesia do Ó',
      venue_name: 'Cariocó Club',
      city: 'São Paulo', state: 'SP', country: 'BR',
    },
    date: daysFromNow(3, 22),
    duration_hours: 6,
    organizer_id: 'fb-organizer-09',
    organizer: 'Cariocó Club',
    source: 'sublinx_partner',
    trust_level: 'partner',
    is_published: true,
    is_expired: false,
    is_secret: false,
    price: 60, currency: 'BRL',
    image_url: 'https://images.unsplash.com/photo-1493676304819-0d7a8d026dcf?w=800',
    short_description: 'Sertanejo universitário e funk no maior complexo de baladas da Zona Norte de São Paulo.',
    current_attendees: 1800,
    ticket_status: 'available',
    has_ticketing: true,
    purchase_url: 'https://www.sympla.com.br',
  },
  {
    id: 'fb-event-010',
    title: 'Espaço das Américas — Festival Eletrônico',
    subtitle: 'Festival de música eletrônica',
    genre: 'techno',
    type: 'festival',
    category: 'festival',
    location: {
      lat: -23.5275, lng: -46.6740,
      address: 'Rua Prof. Milton Rodrigues, 1000 — Barra Funda',
      venue_name: 'Espaço das Américas',
      city: 'São Paulo', state: 'SP', country: 'BR',
    },
    date: daysFromNow(9, 20),
    duration_hours: 11,
    organizer_id: 'fb-organizer-10',
    organizer: 'Américas Live',
    source: 'sublinx_partner',
    trust_level: 'verified',
    is_published: true,
    is_expired: false,
    is_secret: false,
    price: 180, currency: 'BRL',
    image_url: 'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=800',
    short_description: 'Festival de música eletrônica com palcos múltiplos no Espaço das Américas.',
    current_attendees: 3200,
    ticket_status: 'available',
    has_ticketing: true,
    purchase_url: 'https://www.eventbrite.com.br',
  },
  {
    id: 'fb-event-011',
    title: 'Hot Hot — Samba & Pagode',
    subtitle: 'Samba, pagode e MPB',
    genre: 'samba',
    type: 'club',
    category: 'musica',
    location: {
      lat: -23.5450, lng: -46.6380,
      address: 'Alameda Barão de Limeira, 121 — Sé',
      venue_name: 'Hot Hot',
      city: 'São Paulo', state: 'SP', country: 'BR',
    },
    date: daysFromNow(6, 21),
    duration_hours: 5,
    organizer_id: 'fb-organizer-11',
    organizer: 'Hot Hot',
    source: 'sublinx_partner',
    trust_level: 'partner',
    is_published: true,
    is_expired: false,
    is_secret: false,
    price: 55, currency: 'BRL',
    image_url: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=800',
    short_description: 'Samba e pagode com rodas de roda tradicional no centro de São Paulo.',
    current_attendees: 410,
    ticket_status: 'available',
    has_ticketing: true,
    purchase_url: 'https://www.sympla.com.br',
  },
  {
    id: 'fb-event-012',
    title: 'Casa Natura Musical — Indie Night',
    subtitle: 'Indie rock e alternativo',
    genre: 'hip_hop',
    type: 'concert',
    category: 'show',
    location: {
      lat: -23.5250, lng: -46.6740,
      address: 'Rua Palestra Itália, 828 — Pompeia',
      venue_name: 'Casa Natura Musical',
      city: 'São Paulo', state: 'SP', country: 'BR',
    },
    date: daysFromNow(11, 21),
    duration_hours: 4,
    organizer_id: 'fb-organizer-12',
    organizer: 'Natura Musical',
    source: 'sublinx_partner',
    trust_level: 'verified',
    is_published: true,
    is_expired: false,
    is_secret: false,
    price: 95, currency: 'BRL',
    image_url: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800',
    short_description: 'Indie rock e hip hop alternativo na Casa Natura Musical, na Pompeia.',
    current_attendees: 850,
    ticket_status: 'available',
    has_ticketing: true,
    purchase_url: 'https://www.ingresse.com',
  },
  {
    id: 'fb-event-013',
    title: 'Tom Brasil — Show Nacional',
    subtitle: 'Show de banda nacional de sucesso',
    genre: 'rap',
    type: 'concert',
    category: 'show',
    location: {
      lat: -23.5940, lng: -46.6850,
      address: 'Av. das Nações Unidas, 18740 — Vila Olímpia',
      venue_name: 'Tom Brasil',
      city: 'São Paulo', state: 'SP', country: 'BR',
    },
    date: daysFromNow(15, 20),
    duration_hours: 3,
    organizer_id: 'fb-organizer-13',
    organizer: 'Tom Brasil',
    source: 'sublinx_partner',
    trust_level: 'partner',
    is_published: true,
    is_expired: false,
    is_secret: false,
    price: 130, currency: 'BRL',
    image_url: 'https://images.unsplash.com/photo-1506157786151-b8491531f063?w=800',
    short_description: 'Show de banda nacional de sucesso na lendária casa Tom Brasil.',
    current_attendees: 1500,
    ticket_status: 'available',
    has_ticketing: true,
    purchase_url: 'https://www.ticket360.com.br',
  },
  {
    id: 'fb-event-014',
    title: 'The Week — House All Night',
    subtitle: 'House e tech house a noite toda',
    genre: 'house',
    type: 'club',
    category: 'festa',
    location: {
      lat: -23.5900, lng: -46.6500,
      address: 'Rua Gomes de Carvalho, 500 — Vila Olímpia',
      venue_name: 'The Week',
      city: 'São Paulo', state: 'SP', country: 'BR',
    },
    date: daysFromNow(8, 23),
    duration_hours: 10,
    organizer_id: 'fb-organizer-14',
    organizer: 'The Week',
    source: 'sublinx_partner',
    trust_level: 'partner',
    is_published: true,
    is_expired: false,
    is_secret: false,
    price: 100, currency: 'BRL',
    image_url: 'https://images.unsplash.com/photo-1571266028243-d220c6a9f1d4?w=800',
    short_description: 'House e tech house durante a madrugada na The Week, referência da cena eletrônica paulistana.',
    current_attendees: 700,
    ticket_status: 'available',
    has_ticketing: true,
    purchase_url: 'https://shotgun.live',
  },
  {
    id: 'fb-event-015',
    title: 'A Lôca — Underground Techno',
    subtitle: 'Techno e industrial no underground',
    genre: 'techno',
    type: 'underground',
    category: 'musica',
    location: {
      lat: -23.5560, lng: -46.6550,
      address: 'Rua Augusta, 1270 — Consolação',
      venue_name: 'A Lôca',
      city: 'São Paulo', state: 'SP', country: 'BR',
    },
    date: daysFromNow(4, 23),
    duration_hours: 7,
    organizer_id: 'fb-organizer-15',
    organizer: 'A Lôca',
    source: 'sublinx_partner',
    trust_level: 'verified',
    is_published: true,
    is_expired: false,
    is_secret: false,
    price: 65, currency: 'BRL',
    image_url: 'https://images.unsplash.com/photo-1516280440614-37939bbacd81?w=800',
    short_description: 'Techno industrial e experimental no underground da Rua Augusta.',
    current_attendees: 320,
    ticket_status: 'available',
    has_ticketing: true,
    purchase_url: 'https://www.sympla.com.br',
  },
  {
    id: 'fb-event-016',
    title: 'Independente Club — Hip Hop Live',
    subtitle: 'Hip hop e rap ao vivo',
    genre: 'hip_hop',
    type: 'club',
    category: 'show',
    location: {
      lat: -23.5600, lng: -46.6900,
      address: 'Rua Inácio Pereira da Rocha, 306 — Pinheiros',
      venue_name: 'Independente Club',
      city: 'São Paulo', state: 'SP', country: 'BR',
    },
    date: daysFromNow(13, 21),
    duration_hours: 5,
    organizer_id: 'fb-organizer-16',
    organizer: 'Independente Club',
    source: 'sublinx_partner',
    trust_level: 'partner',
    is_published: true,
    is_expired: false,
    is_secret: false,
    price: 75, currency: 'BRL',
    image_url: 'https://images.unsplash.com/photo-1493676304819-0d7a8d026dcf?w=800',
    short_description: 'Hip hop e rap ao vivo com MCs e DJs nacionais em Pinheiros.',
    current_attendees: 280,
    ticket_status: 'available',
    has_ticketing: true,
    purchase_url: 'https://www.ingresse.com',
  },
  {
    id: 'fb-event-017',
    title: 'Clash Club — Dubstep Night',
    subtitle: 'Dubstep e bass music',
    genre: 'dubstep',
    type: 'club',
    category: 'musica',
    location: {
      lat: -23.5270, lng: -46.6690,
      address: 'Rua Augusta, 1230 — Consolação',
      venue_name: 'Clash Club',
      city: 'São Paulo', state: 'SP', country: 'BR',
    },
    date: daysFromNow(16, 23),
    duration_hours: 6,
    organizer_id: 'fb-organizer-17',
    organizer: 'Clash Club',
    source: 'sublinx_partner',
    trust_level: 'verified',
    is_published: true,
    is_expired: false,
    is_secret: false,
    price: 85, currency: 'BRL',
    image_url: 'https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=800',
    short_description: 'Dubstep e bass music com DJs internacionais no Clash Club.',
    current_attendees: 390,
    ticket_status: 'available',
    has_ticketing: true,
    purchase_url: 'https://shotgun.live',
  },
  {
    id: 'fb-event-018',
    title: 'Memorial da América Latina — Festival Cultural',
    subtitle: 'Festival cultural e musical',
    genre: 'experimental',
    type: 'cultural_event',
    category: 'cultural',
    location: {
      lat: -23.5230, lng: -46.6340,
      address: 'Av. Auro Soares de Moura Andrade, 564 — Barra Funda',
      venue_name: 'Memorial da América Latina',
      city: 'São Paulo', state: 'SP', country: 'BR',
    },
    date: daysFromNow(20, 17),
    duration_hours: 8,
    organizer_id: 'fb-organizer-18',
    organizer: 'Memorial SP',
    source: 'sublinx_partner',
    trust_level: 'partner',
    is_published: true,
    is_expired: false,
    is_secret: false,
    price: 50, currency: 'BRL',
    image_url: 'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=800',
    short_description: 'Festival cultural com música experimental, arte e gastronomia no Memorial da América Latina.',
    current_attendees: 1200,
    ticket_status: 'available',
    has_ticketing: true,
    purchase_url: 'https://www.sympla.com.br',
  },
  {
    id: 'fb-event-019',
    title: 'CCBB — Noite de Jazz',
    subtitle: 'Jazz e instrumental',
    genre: 'experimental',
    type: 'concert',
    category: 'cultural',
    location: {
      lat: -23.5480, lng: -46.6340,
      address: 'Rua Álvares Penteado, 112 — Sé',
      venue_name: 'Centro Cultural Banco do Brasil',
      city: 'São Paulo', state: 'SP', country: 'BR',
    },
    date: daysFromNow(19, 19),
    duration_hours: 3,
    organizer_id: 'fb-organizer-19',
    organizer: 'CCBB SP',
    source: 'sublinx_partner',
    trust_level: 'verified',
    is_published: true,
    is_expired: false,
    is_secret: false,
    price: 40, currency: 'BRL',
    image_url: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=800',
    short_description: 'Noite de jazz e música instrumental no Centro Cultural Banco do Brasil.',
    current_attendees: 220,
    ticket_status: 'available',
    has_ticketing: true,
    purchase_url: 'https://www.eventbrite.com.br',
  },
  {
    id: 'fb-event-020',
    title: 'Theatro Municipal — Concerto Sinfônico',
    subtitle: 'Concerto sinfônico e erudito',
    genre: 'experimental',
    type: 'concert',
    category: 'cultural',
    location: {
      lat: -23.5450, lng: -46.6380,
      address: 'Praça Ramos de Azevedo, s/n — República',
      venue_name: 'Theatro Municipal de São Paulo',
      city: 'São Paulo', state: 'SP', country: 'BR',
    },
    date: daysFromNow(25, 20),
    duration_hours: 2,
    organizer_id: 'fb-organizer-20',
    organizer: 'Theatro Municipal',
    source: 'sublinx_partner',
    trust_level: 'partner',
    is_published: true,
    is_expired: false,
    is_secret: false,
    price: 70, currency: 'BRL',
    image_url: 'https://images.unsplash.com/photo-1506157786151-b8491531f063?w=800',
    short_description: 'Concerto sinfônico no histórico Theatro Municipal de São Paulo.',
    current_attendees: 1500,
    ticket_status: 'available',
    has_ticketing: true,
    purchase_url: 'https://www.ticket360.com.br',
  },
  {
    id: 'fb-event-021',
    title: 'Allianz Parque — Show de Arena',
    subtitle: 'Show de arena para 40 mil pessoas',
    genre: 'rap',
    type: 'concert',
    category: 'show',
    location: {
      lat: -23.5270, lng: -46.6690,
      address: 'Rua Francisco Matarazzo, 1705 — Água Branca',
      venue_name: 'Allianz Parque',
      city: 'São Paulo', state: 'SP', country: 'BR',
    },
    date: daysFromNow(30, 19),
    duration_hours: 4,
    organizer_id: 'fb-organizer-21',
    organizer: 'Allianz Live',
    source: 'sublinx_partner',
    trust_level: 'verified',
    is_published: true,
    is_expired: false,
    is_secret: false,
    price: 220, currency: 'BRL',
    image_url: 'https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=800',
    short_description: 'Show de arena com artistas de renome nacional para 40 mil pessoas no Allianz Parque.',
    current_attendees: 38000,
    ticket_status: 'available',
    has_ticketing: true,
    purchase_url: 'https://www.ingresse.com',
  },
  {
    id: 'fb-event-022',
    title: 'Autódromo de Interlagos — Festival Open Air',
    subtitle: 'Festival de música ao ar livre',
    genre: 'techno',
    type: 'festival',
    category: 'festival',
    location: {
      lat: -23.7010, lng: -46.7000,
      address: 'Av. Senador Teotônio Vilela, 261 — Interlagos',
      venue_name: 'Autódromo de Interlagos',
      city: 'São Paulo', state: 'SP', country: 'BR',
    },
    date: daysFromNow(35, 15),
    duration_hours: 12,
    organizer_id: 'fb-organizer-22',
    organizer: 'Interlagos Live',
    source: 'sublinx_partner',
    trust_level: 'partner',
    is_published: true,
    is_expired: false,
    is_secret: false,
    price: 250, currency: 'BRL',
    image_url: 'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=800',
    short_description: 'Festival de música eletrônica ao ar livre no Autódromo de Interlagos.',
    current_attendees: 25000,
    ticket_status: 'available',
    has_ticketing: true,
    purchase_url: 'https://www.eventbrite.com.br',
  },
  {
    id: 'fb-event-023',
    title: 'São Paulo Expo — Feira & Expo',
    subtitle: 'Feira de tecnologia e networking',
    genre: 'experimental',
    type: 'conference',
    category: 'tecnologia',
    location: {
      lat: -23.6800, lng: -46.6900,
      address: 'Rod. dos Imigrantes, km 1,5 — Jabaquara',
      venue_name: 'São Paulo Expo',
      city: 'São Paulo', state: 'SP', country: 'BR',
    },
    date: daysFromNow(17, 10),
    duration_hours: 8,
    organizer_id: 'fb-organizer-23',
    organizer: 'SP Expo',
    source: 'sublinx_partner',
    trust_level: 'verified',
    is_published: true,
    is_expired: false,
    is_secret: false,
    price: 120, currency: 'BRL',
    image_url: 'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=800',
    short_description: 'Feira de tecnologia, startups e networking na São Paulo Expo.',
    current_attendees: 5000,
    ticket_status: 'available',
    has_ticketing: true,
    purchase_url: 'https://www.sympla.com.br',
  },
  {
    id: 'fb-event-024',
    title: 'Madame Society — Indie & Alternative',
    subtitle: 'Indie, alternative e pós-punk',
    genre: 'hip_hop',
    type: 'club',
    category: 'musica',
    location: {
      lat: -23.5560, lng: -46.6550,
      address: 'Rua Augusta, 1089 — Consolação',
      venue_name: 'Madame Society',
      city: 'São Paulo', state: 'SP', country: 'BR',
    },
    date: daysFromNow(2, 23),
    duration_hours: 5,
    organizer_id: 'fb-organizer-24',
    organizer: 'Madame Society',
    source: 'sublinx_partner',
    trust_level: 'partner',
    is_published: true,
    is_expired: false,
    is_secret: false,
    price: 50, currency: 'BRL',
    image_url: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800',
    short_description: 'Indie, alternative e pós-punk na icônica Madame Society da Rua Augusta.',
    current_attendees: 340,
    ticket_status: 'available',
    has_ticketing: true,
    purchase_url: 'https://www.ingresse.com',
  },
  {
    id: 'fb-event-025',
    title: 'Lab Club — Minimal Sessions',
    subtitle: 'Minimal e microhouse',
    genre: 'minimal',
    type: 'club',
    category: 'musica',
    location: {
      lat: -23.5600, lng: -46.6900,
      address: 'Rua dos Pinheiros, 495 — Pinheiros',
      venue_name: 'Lab Club',
      city: 'São Paulo', state: 'SP', country: 'BR',
    },
    date: daysFromNow(14, 23),
    duration_hours: 6,
    organizer_id: 'fb-organizer-25',
    organizer: 'Lab Club',
    source: 'sublinx_partner',
    trust_level: 'verified',
    is_published: true,
    is_expired: false,
    is_secret: false,
    price: 90, currency: 'BRL',
    image_url: 'https://images.unsplash.com/photo-1516280440614-37939bbacd81?w=800',
    short_description: 'Minimal e microhouse com curadoria refinada no Lab Club de Pinheiros.',
    current_attendees: 260,
    ticket_status: 'available',
    has_ticketing: true,
    purchase_url: 'https://shotgun.live',
  },
  {
    id: 'fb-event-026',
    title: 'Praça Victor Civita — Gastronomia & Música',
    subtitle: 'Festival gastronômico com música ao vivo',
    genre: 'experimental',
    type: 'cultural_event',
    category: 'gastronomia',
    location: {
      lat: -23.5260, lng: -46.7010,
      address: 'Rua Artur de Azevedo, 30 — Pinheiros',
      venue_name: 'Praça Victor Civita',
      city: 'São Paulo', state: 'SP', country: 'BR',
    },
    date: daysFromNow(22, 12),
    duration_hours: 8,
    organizer_id: 'fb-organizer-26',
    organizer: 'SP Food Fest',
    source: 'sublinx_partner',
    trust_level: 'partner',
    is_published: true,
    is_expired: false,
    is_secret: false,
    price: 30, currency: 'BRL',
    image_url: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=800',
    short_description: 'Festival gastronômico com food trucks e música ao vivo na Praça Victor Civita.',
    current_attendees: 1800,
    ticket_status: 'available',
    has_ticketing: true,
    purchase_url: 'https://www.sympla.com.br',
  },
  {
    id: 'fb-event-027',
    title: 'Casa das Caldeiras — Rave Industrial',
    subtitle: 'Rave em espaço industrial histórico',
    genre: 'techno',
    type: 'warehouse',
    category: 'festa',
    location: {
      lat: -23.5270, lng: -46.6690,
      address: 'Av. Francisco Matarazzo, 2000 — Barra Funda',
      venue_name: 'Casa das Caldeiras',
      city: 'São Paulo', state: 'SP', country: 'BR',
    },
    date: daysFromNow(24, 23),
    duration_hours: 9,
    organizer_id: 'fb-organizer-27',
    organizer: 'Caldeiras Rave',
    source: 'sublinx_partner',
    trust_level: 'partner',
    is_published: true,
    is_expired: false,
    is_secret: false,
    price: 110, currency: 'BRL',
    image_url: 'https://images.unsplash.com/photo-1485579149621-3123dd979885?w=800',
    short_description: 'Rave techno em espaço industrial tombado pelo patrimônio histórico.',
    current_attendees: 950,
    ticket_status: 'available',
    has_ticketing: true,
    purchase_url: 'https://shotgun.live',
  },
  {
    id: 'fb-event-028',
    title: 'Estádio do Pacaembu — Concerto ao Ar Livre',
    subtitle: 'Concerto beneficente ao ar livre',
    genre: 'reggae',
    type: 'concert',
    category: 'show',
    location: {
      lat: -23.5470, lng: -46.6570,
      address: 'Praça Charles Miller, s/n — Pompeia',
      venue_name: 'Estádio do Pacaembu',
      city: 'São Paulo', state: 'SP', country: 'BR',
    },
    date: daysFromNow(33, 18),
    duration_hours: 5,
    organizer_id: 'fb-organizer-28',
    organizer: 'Pacaembu Live',
    source: 'sublinx_partner',
    trust_level: 'verified',
    is_published: true,
    is_expired: false,
    is_secret: false,
    price: 80, currency: 'BRL',
    image_url: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=800',
    short_description: 'Concerto beneficente de reggae e world music no Estádio do Pacaembu.',
    current_attendees: 15000,
    ticket_status: 'available',
    has_ticketing: true,
    purchase_url: 'https://www.eventbrite.com.br',
  },
  {
    id: 'fb-event-029',
    title: 'Centro Cultural São Paulo — Noite Cultural',
    subtitle: 'Música, arte e performance',
    genre: 'experimental',
    type: 'cultural_event',
    category: 'cultural',
    location: {
      lat: -23.5610, lng: -46.6400,
      address: 'Rua Vergueiro, 1000 — Paraíso',
      venue_name: 'Centro Cultural São Paulo',
      city: 'São Paulo', state: 'SP', country: 'BR',
    },
    date: daysFromNow(12, 19),
    duration_hours: 4,
    organizer_id: 'fb-organizer-29',
    organizer: 'CCSP',
    source: 'sublinx_partner',
    trust_level: 'partner',
    is_published: true,
    is_expired: false,
    is_secret: false,
    is_free: true,
    price: 0, currency: 'BRL',
    image_url: 'https://images.unsplash.com/photo-1506157786151-b8491531f063?w=800',
    short_description: 'Noite cultural com música experimental, arte e performances no CCSP. Entrada gratuita.',
    current_attendees: 600,
    ticket_status: 'available',
    has_ticketing: true,
    purchase_url: 'https://www.sympla.com.br',
  },
  {
    id: 'fb-event-030',
    title: 'Neon Club — Synthwave Party',
    subtitle: 'Synthwave, retrowave e italo',
    genre: 'techno',
    type: 'club',
    category: 'festa',
    location: {
      lat: -23.5560, lng: -46.6550,
      address: 'Rua Augusta, 714 — Consolação',
      venue_name: 'Neon Club',
      city: 'São Paulo', state: 'SP', country: 'BR',
    },
    date: daysFromNow(26, 23),
    duration_hours: 6,
    organizer_id: 'fb-organizer-30',
    organizer: 'Neon Club',
    source: 'sublinx_partner',
    trust_level: 'partner',
    is_published: true,
    is_expired: false,
    is_secret: false,
    price: 70, currency: 'BRL',
    image_url: 'https://images.unsplash.com/photo-1571266028243-d220c6a9f1d4?w=800',
    short_description: 'Synthwave e retrowave com estética anos 80 no Neon Club da Rua Augusta.',
    current_attendees: 420,
    ticket_status: 'available',
    has_ticketing: true,
    purchase_url: 'https://www.ingresse.com',
  },
  {
    id: 'fb-event-031',
    title: 'Saga — Kizomba & Afro Night',
    subtitle: 'Kizomba, semba e afrobeat',
    genre: 'kizomba',
    type: 'club',
    category: 'festa',
    location: {
      lat: -23.5470, lng: -46.6380,
      address: 'Rua Augusta, 473 — Consolação',
      venue_name: 'Saga',
      city: 'São Paulo', state: 'SP', country: 'BR',
    },
    date: daysFromNow(7, 22),
    duration_hours: 5,
    organizer_id: 'fb-organizer-31',
    organizer: 'Saga SP',
    source: 'sublinx_partner',
    trust_level: 'verified',
    is_published: true,
    is_expired: false,
    is_secret: false,
    price: 60, currency: 'BRL',
    image_url: 'https://images.unsplash.com/photo-1493676304819-0d7a8d026dcf?w=800',
    short_description: 'Kizomba, semba e afrobeat com DJs convidados no Saga, no centro de SP.',
    current_attendees: 380,
    ticket_status: 'available',
    has_ticketing: true,
    purchase_url: 'https://www.sympla.com.br',
  },
  {
    id: 'fb-event-032',
    title: 'Parque Ibirapuera — Manhã de Yoga & Ambient',
    subtitle: 'Ambient e chillout ao ar livre',
    genre: 'ambient',
    type: 'cultural_event',
    category: 'social',
    location: {
      lat: -23.5870, lng: -46.6570,
      address: 'Av. Pedro Álvares Cabral — Vila Mariana',
      venue_name: 'Parque Ibirapuera',
      city: 'São Paulo', state: 'SP', country: 'BR',
    },
    date: daysFromNow(9, 8),
    duration_hours: 3,
    organizer_id: 'fb-organizer-32',
    organizer: 'Ibirapuera Wellness',
    source: 'sublinx_partner',
    trust_level: 'partner',
    is_published: true,
    is_expired: false,
    is_secret: false,
    is_free: true,
    price: 0, currency: 'BRL',
    image_url: 'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=800',
    short_description: 'Manhã de yoga e ambient music ao ar livre no Parque Ibirapuera. Entrada gratuita.',
    current_attendees: 320,
    ticket_status: 'available',
    has_ticketing: true,
    purchase_url: 'https://www.eventbrite.com.br',
  },
  {
    id: 'fb-event-033',
    title: 'Cervejaria Nacional — Beer & House',
    subtitle: 'Cerveja artesanal e house music',
    genre: 'house',
    type: 'party',
    category: 'gastronomia',
    location: {
      lat: -23.5760, lng: -46.6890,
      address: 'Av. Brigadeiro Faria Lima, 2232 — Itaim Bibi',
      venue_name: 'Cervejaria Nacional',
      city: 'São Paulo', state: 'SP', country: 'BR',
    },
    date: daysFromNow(5, 19),
    duration_hours: 4,
    organizer_id: 'fb-organizer-33',
    organizer: 'Cervejaria Nacional',
    source: 'sublinx_partner',
    trust_level: 'partner',
    is_published: true,
    is_expired: false,
    is_secret: false,
    price: 45, currency: 'BRL',
    image_url: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=800',
    short_description: 'Cerveja artesanal e house music na Cervejaria Nacional, no coração da Faria Lima.',
    current_attendees: 250,
    ticket_status: 'available',
    has_ticketing: true,
    purchase_url: 'https://www.sympla.com.br',
  },
  {
    id: 'fb-event-034',
    title: 'Vila Madalena — Street Party',
    subtitle: 'Festa de rua em Vila Madalena',
    genre: 'funk',
    type: 'party',
    category: 'festa',
    location: {
      lat: -23.5550, lng: -46.6900,
      address: 'Rua Aspicuelta, 400 — Vila Madalena',
      venue_name: 'Beco do Batman',
      city: 'São Paulo', state: 'SP', country: 'BR',
    },
    date: daysFromNow(11, 18),
    duration_hours: 7,
    organizer_id: 'fb-organizer-34',
    organizer: 'Vila Madalena Fest',
    source: 'sublinx_partner',
    trust_level: 'verified',
    is_published: true,
    is_expired: false,
    is_secret: false,
    price: 0, currency: 'BRL',
    image_url: 'https://images.unsplash.com/photo-1493676304819-0d7a8d026dcf?w=800',
    short_description: 'Festa de rua aberta com funk, trap e arte urbana no coração da Vila Madalena.',
    current_attendees: 2200,
    ticket_status: 'available',
    has_ticketing: true,
    purchase_url: 'https://shotgun.live',
  },
  {
    id: 'fb-event-035',
    title: 'Estádio do Morumbi — Show Gigante',
    subtitle: 'Show para 60 mil fãs',
    genre: 'rap',
    type: 'concert',
    category: 'show',
    location: {
      lat: -23.6010, lng: -46.7210,
      address: 'Praça Roberto Gomes Pedrosa, 1 — Morumbi',
      venue_name: 'Estádio Cícero Pompeu de Toledo',
      city: 'São Paulo', state: 'SP', country: 'BR',
    },
    date: daysFromNow(40, 19),
    duration_hours: 4,
    organizer_id: 'fb-organizer-35',
    organizer: 'Morumbi Live',
    source: 'sublinx_partner',
    trust_level: 'verified',
    is_published: true,
    is_expired: false,
    is_secret: false,
    price: 300, currency: 'BRL',
    image_url: 'https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=800',
    short_description: 'Show de gigante do rap nacional para 60 mil fãs no Estádio do Morumbi.',
    current_attendees: 55000,
    ticket_status: 'available',
    has_ticketing: true,
    purchase_url: 'https://www.ingresse.com',
  },
  {
    id: 'fb-event-036',
    title: 'MUBE — Noite de Arte & Música',
    subtitle: 'Arte contemporânea e ambient',
    genre: 'ambient',
    type: 'exhibition',
    category: 'cultural',
    location: {
      lat: -23.5700, lng: -46.6900,
      address: 'Av. Pedroso de Morais, 899 — Pinheiros',
      venue_name: 'Museu Brasileiro de Escultura (MUBE)',
      city: 'São Paulo', state: 'SP', country: 'BR',
    },
    date: daysFromNow(18, 20),
    duration_hours: 3,
    organizer_id: 'fb-organizer-36',
    organizer: 'MUBE',
    source: 'sublinx_partner',
    trust_level: 'partner',
    is_published: true,
    is_expired: false,
    is_secret: false,
    price: 35, currency: 'BRL',
    image_url: 'https://images.unsplash.com/photo-1506157786151-b8491531f063?w=800',
    short_description: 'Noite de arte contemporânea e ambient music no MUBE.',
    current_attendees: 180,
    ticket_status: 'available',
    has_ticketing: true,
    purchase_url: 'https://www.sympla.com.br',
  },
  {
    id: 'fb-event-037',
    title: 'Audio Club — Hard Techno Special',
    subtitle: 'Hardcore e techno industrial',
    genre: 'hardcore',
    type: 'club',
    category: 'musica',
    location: {
      lat: -23.5270, lng: -46.6690,
      address: 'Av. Francisco Matarazzo, 694 — Barra Funda',
      venue_name: 'Audio Club',
      city: 'São Paulo', state: 'SP', country: 'BR',
    },
    date: daysFromNow(27, 23),
    duration_hours: 8,
    organizer_id: 'fb-organizer-37',
    organizer: 'Audio Club',
    source: 'sublinx_partner',
    trust_level: 'partner',
    is_published: true,
    is_expired: false,
    is_secret: false,
    price: 95, currency: 'BRL',
    image_url: 'https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=800',
    short_description: 'Edição especial de hard techno e industrial no Audio Club com lineup internacional.',
    current_attendees: 520,
    ticket_status: 'available',
    has_ticketing: true,
    purchase_url: 'https://shotgun.live',
  },
  {
    id: 'fb-event-038',
    title: 'D-Edge — Deep House All Nighter',
    subtitle: 'Deep house a madrugada toda',
    genre: 'house',
    type: 'club',
    category: 'musica',
    location: {
      lat: -23.5945, lng: -46.6835,
      address: 'Av. Antônio Joaquim de Moura Andrade, 1211 — Vila Olímpia',
      venue_name: 'D-Edge',
      city: 'São Paulo', state: 'SP', country: 'BR',
    },
    date: daysFromNow(19, 23),
    duration_hours: 10,
    organizer_id: 'fb-organizer-38',
    organizer: 'D-Edge',
    source: 'sublinx_partner',
    trust_level: 'partner',
    is_published: true,
    is_expired: false,
    is_secret: false,
    price: 130, currency: 'BRL',
    image_url: 'https://images.unsplash.com/photo-1571266028243-d220c6a9f1d4?w=800',
    short_description: 'Deep house a madrugada toda no D-Edge com resident DJs internacionais.',
    current_attendees: 410,
    ticket_status: 'available',
    has_ticketing: true,
    purchase_url: 'https://www.ingresse.com',
  },
  {
    id: 'fb-event-039',
    title: 'Cine Joia — Trap & Drill Live',
    subtitle: 'Trap e drill ao vivo',
    genre: 'trap',
    type: 'concert',
    category: 'show',
    location: {
      lat: -23.5495, lng: -46.6360,
      address: 'Praça Carlos Gomes, 130 — Sé',
      venue_name: 'Cine Joia',
      city: 'São Paulo', state: 'SP', country: 'BR',
    },
    date: daysFromNow(23, 22),
    duration_hours: 4,
    organizer_id: 'fb-organizer-39',
    organizer: 'Cine Joia',
    source: 'sublinx_partner',
    trust_level: 'verified',
    is_published: true,
    is_expired: false,
    is_secret: false,
    price: 85, currency: 'BRL',
    image_url: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800',
    short_description: 'Trap e drill ao vivo com artistas do cenário nacional no Cine Joia.',
    current_attendees: 380,
    ticket_status: 'available',
    has_ticketing: true,
    purchase_url: 'https://www.ticket360.com.br',
  },
  {
    id: 'fb-event-040',
    title: 'Komplexo Tempo — Kuduro Bash',
    subtitle: 'Kuduro, afrohouse e batida',
    genre: 'kuduro',
    type: 'club',
    category: 'festa',
    location: {
      lat: -23.5560, lng: -46.6550,
      address: 'Rua Augusta, 967 — Consolação',
      venue_name: 'Komplexo Tempo',
      city: 'São Paulo', state: 'SP', country: 'BR',
    },
    date: daysFromNow(6, 23),
    duration_hours: 7,
    organizer_id: 'fb-organizer-40',
    organizer: 'Komplexo Tempo',
    source: 'sublinx_partner',
    trust_level: 'partner',
    is_published: true,
    is_expired: false,
    is_secret: false,
    price: 75, currency: 'BRL',
    image_url: 'https://images.unsplash.com/photo-1493676304819-0d7a8d026dcf?w=800',
    short_description: 'Kuduro, afrohouse e batida angolana com DJs convidados no Komplexo Tempo.',
    current_attendees: 450,
    ticket_status: 'available',
    has_ticketing: true,
    purchase_url: 'https://www.sympla.com.br',
  },
  {
    id: 'fb-event-041',
    title: 'Villa Country — Pagode Sunday',
    subtitle: 'Pagode e samba de domingo',
    genre: 'pagode',
    type: 'club',
    category: 'musica',
    location: {
      lat: -23.5230, lng: -46.7010,
      address: 'Rua Cardeal Arcoverde, 3000 — Pinheiros',
      venue_name: 'Villa Country',
      city: 'São Paulo', state: 'SP', country: 'BR',
    },
    date: daysFromNow(10, 16),
    duration_hours: 5,
    organizer_id: 'fb-organizer-41',
    organizer: 'Villa Country',
    source: 'sublinx_partner',
    trust_level: 'partner',
    is_published: true,
    is_expired: false,
    is_secret: false,
    price: 65, currency: 'BRL',
    image_url: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=800',
    short_description: 'Pagode e samba de domingo à tarde no tradicional Villa Country.',
    current_attendees: 340,
    ticket_status: 'available',
    has_ticketing: true,
    purchase_url: 'https://www.sympla.com.br',
  },
  {
    id: 'fb-event-042',
    title: 'Parque Ibirapuera — Run & Drum Bass',
    subtitle: 'Corrida matinal com drum & bass',
    genre: 'drum_bass',
    type: 'sport_event',
    category: 'esporte',
    location: {
      lat: -23.5870, lng: -46.6570,
      address: 'Av. Pedro Álvares Cabral — Vila Mariana',
      venue_name: 'Parque Ibirapuera',
      city: 'São Paulo', state: 'SP', country: 'BR',
    },
    date: daysFromNow(8, 7),
    duration_hours: 3,
    organizer_id: 'fb-organizer-42',
    organizer: 'Ibirapuera Run',
    source: 'sublinx_partner',
    trust_level: 'verified',
    is_published: true,
    is_expired: false,
    is_secret: false,
    price: 40, currency: 'BRL',
    image_url: 'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=800',
    short_description: 'Corrida matinal ao som de drum & bass com DJs ao vivo no Parque Ibirapuera.',
    current_attendees: 500,
    ticket_status: 'available',
    has_ticketing: true,
    purchase_url: 'https://www.eventbrite.com.br',
  },
  {
    id: 'fb-event-043',
    title: 'Laroc Club — Techno Day Party',
    subtitle: 'Techno de pool party',
    genre: 'techno',
    type: 'party',
    category: 'festa',
    location: {
      lat: -23.6240, lng: -46.7000,
      address: 'Rua Tucanos, 260 — Chácara Santo Antônio',
      venue_name: 'Laroc Club',
      city: 'São Paulo', state: 'SP', country: 'BR',
    },
    date: daysFromNow(15, 14),
    duration_hours: 8,
    organizer_id: 'fb-organizer-43',
    organizer: 'Laroc Club',
    source: 'sublinx_partner',
    trust_level: 'partner',
    is_published: true,
    is_expired: false,
    is_secret: false,
    price: 120, currency: 'BRL',
    image_url: 'https://images.unsplash.com/photo-1571266028243-d220c6a9f1d4?w=800',
    short_description: 'Techno day party com pool party e lineup internacional no Laroc Club.',
    current_attendees: 680,
    ticket_status: 'available',
    has_ticketing: true,
    purchase_url: 'https://shotgun.live',
  },
  {
    id: 'fb-event-044',
    title: 'Vale do Anhangabaú — Carnaval SP',
    subtitle: 'Blocos de carnaval ao ar livre',
    genre: 'samba',
    type: 'festival',
    category: 'cultural',
    location: {
      lat: -23.5430, lng: -46.6380,
      address: 'Vale do Anhangabaú — Centro',
      venue_name: 'Vale do Anhangabaú',
      city: 'São Paulo', state: 'SP', country: 'BR',
    },
    date: daysFromNow(45, 10),
    duration_hours: 12,
    organizer_id: 'fb-organizer-44',
    organizer: 'Carnaval SP',
    source: 'sublinx_partner',
    trust_level: 'verified',
    is_published: true,
    is_expired: false,
    is_secret: false,
    is_free: true,
    price: 0, currency: 'BRL',
    image_url: 'https://images.unsplash.com/photo-1493676304819-0d7a8d026dcf?w=800',
    short_description: 'Desfile de blocos de carnaval com samba e marchinhas no Vale do Anhangabaú. Entrada gratuita.',
    current_attendees: 15000,
    ticket_status: 'available',
    has_ticketing: true,
    purchase_url: 'https://www.eventbrite.com.br',
  },
  {
    id: 'fb-event-045',
    title: 'Clash Club — Ambient & Drone',
    subtitle: 'Ambient, drone e experimental',
    genre: 'ambient',
    type: 'club',
    category: 'musica',
    location: {
      lat: -23.5270, lng: -46.6690,
      address: 'Rua Augusta, 1230 — Consolação',
      venue_name: 'Clash Club',
      city: 'São Paulo', state: 'SP', country: 'BR',
    },
    date: daysFromNow(29, 21),
    duration_hours: 4,
    organizer_id: 'fb-organizer-45',
    organizer: 'Clash Club',
    source: 'sublinx_partner',
    trust_level: 'partner',
    is_published: true,
    is_expired: false,
    is_secret: false,
    price: 55, currency: 'BRL',
    image_url: 'https://images.unsplash.com/photo-1506157786151-b8491531f063?w=800',
    short_description: 'Ambient, drone e experimental com som imersivo no Clash Club.',
    current_attendees: 220,
    ticket_status: 'available',
    has_ticketing: true,
    purchase_url: 'https://www.ingresse.com',
  },
  {
    id: 'fb-event-046',
    title: 'Espaço das Américas — Rock Festival',
    subtitle: 'Rock, punk e metal',
    genre: 'rap',
    type: 'festival',
    category: 'festival',
    location: {
      lat: -23.5275, lng: -46.6740,
      address: 'Rua Prof. Milton Rodrigues, 1000 — Barra Funda',
      venue_name: 'Espaço das Américas',
      city: 'São Paulo', state: 'SP', country: 'BR',
    },
    date: daysFromNow(38, 17),
    duration_hours: 10,
    organizer_id: 'fb-organizer-46',
    organizer: 'Américas Live',
    source: 'sublinx_partner',
    trust_level: 'verified',
    is_published: true,
    is_expired: false,
    is_secret: false,
    price: 200, currency: 'BRL',
    image_url: 'https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=800',
    short_description: 'Festival de rock, punk e metal com bandas nacionais e internacionais no Espaço das Américas.',
    current_attendees: 4200,
    ticket_status: 'available',
    has_ticketing: true,
    purchase_url: 'https://www.ticket360.com.br',
  },
  {
    id: 'fb-event-047',
    title: 'A Lôca — Minimal & Acid All Night',
    subtitle: 'Minimal e acid a noite toda',
    genre: 'acid',
    type: 'underground',
    category: 'musica',
    location: {
      lat: -23.5560, lng: -46.6550,
      address: 'Rua Augusta, 1270 — Consolação',
      venue_name: 'A Lôca',
      city: 'São Paulo', state: 'SP', country: 'BR',
    },
    date: daysFromNow(31, 23),
    duration_hours: 8,
    organizer_id: 'fb-organizer-47',
    organizer: 'A Lôca',
    source: 'sublinx_partner',
    trust_level: 'partner',
    is_published: true,
    is_expired: false,
    is_secret: false,
    price: 70, currency: 'BRL',
    image_url: 'https://images.unsplash.com/photo-1485579149621-3123dd979885?w=800',
    short_description: 'Minimal e acid house durante a madrugada no underground da Rua Augusta.',
    current_attendees: 300,
    ticket_status: 'available',
    has_ticketing: true,
    purchase_url: 'https://www.sympla.com.br',
  },
  {
    id: 'fb-event-048',
    title: 'Cine Joia — Noite de Reggae',
    subtitle: 'Reggae roots e dub',
    genre: 'reggae',
    type: 'concert',
    category: 'show',
    location: {
      lat: -23.5495, lng: -46.6360,
      address: 'Praça Carlos Gomes, 130 — Sé',
      venue_name: 'Cine Joia',
      city: 'São Paulo', state: 'SP', country: 'BR',
    },
    date: daysFromNow(21, 20),
    duration_hours: 4,
    organizer_id: 'fb-organizer-48',
    organizer: 'Cine Joia',
    source: 'sublinx_partner',
    trust_level: 'verified',
    is_published: true,
    is_expired: false,
    is_secret: false,
    price: 75, currency: 'BRL',
    image_url: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=800',
    short_description: 'Noite de reggae roots e dub com bandas nacionais no histórico Cine Joia.',
    current_attendees: 290,
    ticket_status: 'available',
    has_ticketing: true,
    purchase_url: 'https://www.ingresse.com',
  },
  {
    id: 'fb-event-049',
    title: 'Hot Hot — Hip Hop & Funk de Rua',
    subtitle: 'Hip hop e funk de rua',
    genre: 'funk',
    type: 'club',
    category: 'festa',
    location: {
      lat: -23.5450, lng: -46.6380,
      address: 'Alameda Barão de Limeira, 121 — Sé',
      venue_name: 'Hot Hot',
      city: 'São Paulo', state: 'SP', country: 'BR',
    },
    date: daysFromNow(13, 23),
    duration_hours: 6,
    organizer_id: 'fb-organizer-49',
    organizer: 'Hot Hot',
    source: 'sublinx_partner',
    trust_level: 'partner',
    is_published: true,
    is_expired: false,
    is_secret: false,
    price: 50, currency: 'BRL',
    image_url: 'https://images.unsplash.com/photo-1493676304819-0d7a8d026dcf?w=800',
    short_description: 'Hip hop e funk de rua com MCs convidados no centro de São Paulo.',
    current_attendees: 360,
    ticket_status: 'available',
    has_ticketing: true,
    purchase_url: 'https://www.sympla.com.br',
  },
  {
    id: 'fb-event-050',
    title: 'Parque Ibirapuera — Festival Ambiental',
    subtitle: 'Festival de sustentabilidade e música',
    genre: 'experimental',
    type: 'festival',
    category: 'cultural',
    location: {
      lat: -23.5870, lng: -46.6570,
      address: 'Av. Pedro Álvares Cabral — Vila Mariana',
      venue_name: 'Parque Ibirapuera',
      city: 'São Paulo', state: 'SP', country: 'BR',
    },
    date: daysFromNow(42, 11),
    duration_hours: 9,
    organizer_id: 'fb-organizer-50',
    organizer: 'Ibirapuera Verde',
    source: 'sublinx_partner',
    trust_level: 'partner',
    is_published: true,
    is_expired: false,
    is_secret: false,
    is_free: true,
    price: 0, currency: 'BRL',
    image_url: 'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=800',
    short_description: 'Festival de sustentabilidade, música experimental e educação ambiental no Parque Ibirapuera. Entrada gratuita.',
    current_attendees: 3500,
    ticket_status: 'available',
    has_ticketing: true,
    purchase_url: 'https://www.eventbrite.com.br',
  },
];