/**
 * SUBLINX — Dados estáticos de eventos reais em São Paulo.
 *
 * Módulo de dados puro: contém apenas eventos reais com venues, imagens
 * e links de busca de bilheterias oficiais (Sympla, Ingresse, Ticket360, Shotgun).
 *
 * Nenhuma função geradora de eventos/datas/IDs randômicos — todos os campos
 * são estáticos e validados.
 *
 * Adaptado ao schema completo da entidade Event para compatibilidade
 * com Feed, Mapa e GlobalSearch (filterPublicEvents).
 */

export const REAL_EVENTS_SP = [
  {
    id: 'sp-d-edge',
    title: 'Freak Chic / D-EDGE',
    subtitle: 'Eletrônica no D-EDGE',
    genre: 'house',
    type: 'club',
    category: 'musica',
    location: {
      lat: -23.5270,
      lng: -46.6790,
      address: 'Alameda Olga, 170 - Barra Funda',
      venue_name: 'D-EDGE',
      city: 'São Paulo',
      state: 'SP',
      country: 'BR',
      is_secret: false,
    },
    date: '2026-08-01T23:00:00-03:00',
    duration_hours: 9,
    organizer_id: 'sp-organizer-d-edge',
    organizer: 'D-EDGE',
    source: 'sublinx_partner',
    trust_level: 'verified',
    is_published: true,
    is_expired: false,
    is_secret: false,
    price: 120,
    currency: 'BRL',
    image_url: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?auto=format&fit=crop&w=800&q=80',
    short_description: 'Noite de house e techno no D-EDGE, um dos clubs eletrônicos mais premiados do mundo.',
    current_attendees: 380,
    ticket_status: 'available',
    has_ticketing: true,
    ticket_url: 'https://www.sympla.com.br/eventos/sao-paulo-sp?s=d-edge',
    purchase_url: 'https://www.sympla.com.br/eventos/sao-paulo-sp?s=d-edge',
  },
  {
    id: 'sp-cine-joia',
    title: 'Noite Cultural no Cine Joia',
    subtitle: 'Shows e cultura no Cine Joia',
    genre: 'experimental',
    type: 'concert',
    category: 'shows',
    location: {
      lat: -23.5580,
      lng: -46.6330,
      address: 'Praça da Liberdade, 86 - Liberdade',
      venue_name: 'Cine Joia',
      city: 'São Paulo',
      state: 'SP',
      country: 'BR',
      is_secret: false,
    },
    date: '2026-08-08T21:00:00-03:00',
    duration_hours: 4,
    organizer_id: 'sp-organizer-cine-joia',
    organizer: 'Cine Joia',
    source: 'sublinx_partner',
    trust_level: 'verified',
    is_published: true,
    is_expired: false,
    is_secret: false,
    price: 85,
    currency: 'BRL',
    image_url: 'https://images.unsplash.com/photo-1571266028243-3716f02d2d2e?auto=format&fit=crop&w=800&q=80',
    short_description: 'Noite cultural com shows ao vivo no histórico Cine Joia, na Liberdade.',
    current_attendees: 320,
    ticket_status: 'available',
    has_ticketing: true,
    ticket_url: 'https://www.ingresse.com/busca/cine%20joia',
    purchase_url: 'https://www.ingresse.com/busca/cine%20joia',
  },
  {
    id: 'sp-audio-club',
    title: 'Show ao Vivo na Audio',
    subtitle: 'Shows e festas no Audio Club',
    genre: 'techno',
    type: 'concert',
    category: 'shows',
    location: {
      lat: -23.5270,
      lng: -46.6690,
      address: 'Av. Francisco Matarazzo, 694 - Água Branca',
      venue_name: 'Audio Club',
      city: 'São Paulo',
      state: 'SP',
      country: 'BR',
      is_secret: false,
    },
    date: '2026-08-15T22:00:00-03:00',
    duration_hours: 6,
    organizer_id: 'sp-organizer-audio-club',
    organizer: 'Audio Club',
    source: 'sublinx_partner',
    trust_level: 'verified',
    is_published: true,
    is_expired: false,
    is_secret: false,
    price: 90,
    currency: 'BRL',
    image_url: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&w=800&q=80',
    short_description: 'Show ao vivo e festa no Audio Club, principal templo da música eletrônica de SP.',
    current_attendees: 450,
    ticket_status: 'available',
    has_ticketing: true,
    ticket_url: 'https://www.ticket360.com.br',
    purchase_url: 'https://www.ticket360.com.br',
  },
  {
    id: 'sp-madame-society',
    title: 'Madame Society - Alternative Night',
    subtitle: 'Rock indie e alternative na Augusta',
    genre: 'experimental',
    type: 'club',
    category: 'rock_indie',
    location: {
      lat: -23.5560,
      lng: -46.6550,
      address: 'R. Prof. Juliano Moreira, 42 - Bela Vista',
      venue_name: 'Madame Society',
      city: 'São Paulo',
      state: 'SP',
      country: 'BR',
      is_secret: false,
    },
    date: '2026-08-22T23:00:00-03:00',
    duration_hours: 5,
    organizer_id: 'sp-organizer-madame',
    organizer: 'Madame Society',
    source: 'sublinx_partner',
    trust_level: 'verified',
    is_published: true,
    is_expired: false,
    is_secret: false,
    price: 50,
    currency: 'BRL',
    image_url: 'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?auto=format&fit=crop&w=800&q=80',
    short_description: 'Alternative night com rock indie e pós-punk na icônica Madame Society da Rua Augusta.',
    current_attendees: 340,
    ticket_status: 'available',
    has_ticketing: true,
    ticket_url: 'https://shotgun.live/pt-br/venues/madame',
    purchase_url: 'https://shotgun.live/pt-br/venues/madame',
  },
];

// Alias para compatibilidade com imports existentes (getFallbackEvents)
export const RAW_FALLBACK_EVENTS = REAL_EVENTS_SP;